//"use client";
//import {useState} from 'react';
import BottomBar from './BottomBar';

function generatePageTitle(pageTitle) {
    let meta = {
      title: pageTitle,
      description: "Generated by create next app",
    }
    return meta;
};

export default function BottomMenu({ pageTitle, children }) {
    let titleConcat = "PTPal";

    if (pageTitle) titleConcat = pageTitle + " | " + titleConcat;
    //const [showSidebar, setShowSidebar] = useState(false);
    //console.log("aaa: " + titleConcat);
    let abc = generatePageTitle(titleConcat);
    //abc = abc.title;
    //console.log("bottomMenu index: " + abc.title);
    return (
        <div className="flex flex-col flex-grow w-screen h-screen">
            {children}
            <BottomBar></BottomBar>
        </div>
    )
}
